### ISSUE TITLE
Create Dashboard

### ISSUE THREAD

**Issue by AyushExel** [lancedb/yoloexplorer#12]
Allows users to plot images, analytics and embeddings in interactive browser plots. the current solution (matplotlib) isn't scalable.
The best candidate that I found was plotly dash(https://dash.plotly.com/) but there might be more so open to suggestions.
The idea is avoid building the UI from scratch using js/node as it'll make installation complex and development slow.

**Comment by hardikdava** [comment]
Thanks @AyushExel. I will take a look.

**Comment by hardikdava** [comment]
Hi @AyushExel :wave: , I can suggest following to build dashboard. Of course it depends, what type of dashboard you want to make?

- [Streamlit](https://streamlit.io/)  -> Highly scalabel, even multipage options, 3D plots(for embedding visualization)
- [Plotly](https://dash.plotly.com/)
- [Gradio](https://www.gradio.app/)

Let me know your views and thoughts on how to go ahead. I can definitely help you with this.

**Comment by AyushExel** [comment]
@hardikdava Thanks. I've used streamlit a little in the past, back then there was no state management. has that improved now?
What I want to build is a simple dashboard that can be used to plot the dataset(images) and maybe a few plots.
The main deal here is to be able to enable infinite scrolling so that the images displayed are of the fixed(original size) unlike matplotliob that just shrinks them to fit in a fixed frame

**Comment by hardikdava** [comment]
@AyushExel yeah, they have added state management look [here](https://docs.streamlit.io/library/api-reference/session-state). I think scrolling won't be an issue with streamlit.

**Comment by AyushExel** [comment]
@hardikdava okay perfect! Would you like to start working on this? I'll be happy to collaborate. 
Add a top level folder `/frontend' in the `yoloexplorer` folder and we can start to plan the dashboard there. What do you think?

**Comment by AyushExel** [comment]
Perfect make a PR when you're ready
