### ISSUE TITLE
How to use own dataset?

### ISSUE THREAD

**Issue by Oliver-Douz** [lancedb/yoloexplorer#39]
Hi there! Thanks for the great work! 

If we want to use our own dataset, what should be included in the dataset? I mean, the directory format, labels, etc. Considering we have a dataset of images for a park, should we also have the labels for these images?

Hope this is not a stupid problem : )

Best regards,
Zijia

**Comment by AyushExel** [comment]
@Oliver-Douz You should be able to simply pass your custom dataset's .yaml file in the Explorer object like this:
```
exp = Explorer("path/to/data.yaml")
```
Let me know if this doesn't work.

**Comment by AyushExel** [comment]
Closing this. Please let me know if you have some other issues
